hotelsite/guest/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.guest_home, name='guest_home'),
    path('myinfo', views.guest_myinfo, name = 'guest_myinfo'),
    path('payment', views.guest_payment, name='payment'),
    path('room', views.guest_room, name='guest_room'),
]

hotelsite/hotelsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('guest/', include('guest.urls')),
    path('', include('staff.urls')) # index
]

hotelsite/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.sign_in, name='sign_in'),
]

hotelsite/staff/urls.py
from django.urls import path
from . import views
from login import views as login_views

app_name = 'staff'
urlpatterns = [
    path('', views.staff_home, name='staff_home'),
    path('login', login_views.log_out, name="logout"),
    path('guest_req', views.guest_req, name='guest_req'),
    path('guest_req/new', views.post_new, name = 'post_new'),
    path('guest_req/<pk>', views.post_detail, name='post_detail'),

]

hotelsite/guest/models.py
from django.db import models

# Create your models here.

hotelsite/login/models.py
from django.db import models 
from django.utils import timezone

# class Guest(models.Model): 
#     guest_id = models.CharField(max_length=10) 
#     guest_pw = models.CharField(max_length=10)
#     first_name = models.CharField(max_length=10) 
#     last_name = models.CharField(max_length=10) 
#     date_of_birth = models.DateField(default=timezone.now)  # 1998/01/01 
#     sex = models.CharField(max_length=1)    # F 
#     phone_num = models.CharField(max_length=13)     # 010-0000-0000 
#     e_mail = models.CharField(max_length=50) 
#     language = models.CharField(max_length=20)    #Korea//1차 발표때 나온 지적에 따라 선호 언어로 변경 
#     guest_class = models.CharField(max_length=10)   #silver 

#     def __str__(self):
#         return self.guest_id

# class Staff(models.Model):
#     staff_id = models.IntegerField()
#     staff_pw = models.IntegerField()
#     first_name = models.CharField(max_length=10) 
#     last_name = models.CharField(max_length=10) 
#     work_start_time = models.CharField(max_length=20)   # 11/21 09:00 
#     work_end_time = models.CharField(max_length=20) # 11/21 18:00 
#     work_weekday = models.CharField(max_length=3)   # 월요일 
#     date_of_birth = models.CharField(max_length=10)  # 1998/01/01 
#     sex = models.CharField(max_length=1)    # F 
#     status = models.IntegerField()  # 0 : not working, 1 : working 
#     phone_num = models.CharField(max_length=13)     # 010-0000-0000 
#     # photo = models.FileField(upload_to=path) 
#     # dept = models.ForeignKey(Department, on_delete=models.CASCADE)  # it needs to check whethere it is foreign key  

#     def __str__(self):
#         return self.staff_id

hotelsite/staff/models.py
from django.db import models
from django.utils import timezone

class Room(models.Model): 
 
    TYPE_IN_CHOICES=(
        ('SINGLE', 'Single'),
        ('DOUBLE', 'Double'),
        ('SUITE', 'Suite')
    )
    
    STATUS_CLEAN_IN_CHOICES=(
        ('CLEAN', 'Clean'),
        ('UNCLEAN', 'Unclean')
    )
    room_num = models.DecimalField(decimal_places=0, max_digits=4, primary_key = 'True') 
    room_type = models.CharField(max_length=10, choices=TYPE_IN_CHOICES, default = 'SINGLE') #Suite 
    status_clean = models.CharField(max_length=10, choices=STATUS_CLEAN_IN_CHOICES, default='CLEAN')  # 0 : 사용중, 1 : 사용가능, 3 : 청소 필요, 4 : 예약

    def __str__(self):
        return str(self.room_num)+'호'

class Department(models.Model): 
    name = models.CharField(max_length = 30) 
    role = models.TextField() 
    tel_num = models.CharField(max_length = 20) 

    def __str__(self): 
        return self.name 

class Request_post(models.Model): 
    #처리여부 옵션
    UNASSIGNED = 1
    NOT_YET=2
    DONE=3

    HANDLE_IN_CHOICES=(
        (UNASSIGNED, '미배정'),
        (NOT_YET, '처리중'),
        (DONE, '처리완료'),
    )

    #요청번호는 자체 제공하는 pk이용 
    author =  models.ForeignKey('auth.User', on_delete=models.CASCADE) 
    title = models.TextField() 
    text = models.TextField() 
    created_date = models.DateTimeField(default=timezone.now) 
    dept = models.ForeignKey('Department',on_delete=models.CASCADE, blank = True, null=True)
    room_num = models.ForeignKey('Room', on_delete=models.CASCADE, blank = True, null = True) 
    handle_or_not = models.DecimalField(decimal_places=0, max_digits=4, choices=HANDLE_IN_CHOICES, default = UNASSIGNED)

    def __str__(self): 
        return self.title 


hotelsite/login/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

hotelsite/staff/forms.py
from django import forms
from .models import Request_post, Department, Room

class PostForm(forms.ModelForm):
    class Meta:
        model = Request_post
        fields = ('room_num','author', 'title', 'text','dept')

hotelsite/guest/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


def guest_home(request):
    return render(request, 'guest/guest_home.html')

def guest_myinfo(request):
    return render(request, 'guest/guest_myinfo.html')

def guest_payment(request):
    return render(request, 'guest/payment.html')

def guest_room(request):
    return render(request, 'guest/guest_room.html')

hotelsite/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from .forms import LoginForm
from django.contrib.auth.decorators import login_required


def sign_in(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        print(user)

        if user is not None:
            login(request, user)
            return redirect('../')
        else:
            return render(request, 'sign_in/log_in.html')
    else:
        form = LoginForm()
        return render(request, 'sign_in/log_in.html', {'form':form})

@login_required(login_url='login:sign_in')
def log_out(request):
    logout(request)
    return redirect('login:sign_in')

hotelsite/staff/views.py
from django.shortcuts import render, get_object_or_404
from .models import Room, Request_post, Department
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from django.http import HttpResponse

@login_required(login_url='login:sign_in')
def staff_home(request):
    rooms = Room.objects.order_by('room_num')
    return render(request, 'staff/staff_home.html', {'rooms':rooms})

def guest_req(request): 
    posts = Request_post.objects.order_by('handle_or_not') 
    form = PostForm()
    return render(request, 'staff/guest_req.html', {'posts': posts,'form':form})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            if post.dept != None:
                post.handle_or_not= 2
            post.save()
            return redirect('staff:guest_req')
    else:
        form = PostForm()
    return render(request, 'staff/req_edit.html', {'form':form})

def post_detail(request, pk):
    post = get_object_or_404(Request_post, pk=pk)
    if request.method == "POST":
        if request.POST['dept'] != '':
            dept = Department.objects.get(id=request.POST['dept'])
            post.dept = dept
            post.handle_or_not = 2

        else:
            post.dept = None
            post.handle_or_not = 1
        post.save()
        return redirect('staff:guest_req')
    else:
        form = PostForm(instance=post)
        return render(request, 'staff/req_detail.html', {'post':post, 'form':form})

hotelsite/guest/templates/guest/guest_base.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'Wallpaper_2560x1440.ico' %}">

    <title>Hotel Guest</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
  
    <!-- Custom styles for this template -->
    <link href="http://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'blog.css' %}" rel="stylesheet">
   
  </head>

  <body>

    <div class="container">

      
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#"></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'guest_home' %}">Hotel</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
          
            <a class="btn btn-sm btn-outline-secondary" href="#">logout</a>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="{% url 'guest_myinfo' %}">내 정보</a>
          <a class="p-2 text-muted" href="#">예약 확인</a>
          <a class="p-2 text-muted" href="#">직원 검색</a>
          <a class="p-2 text-muted" href="#">방 정보</a>
          <a class="p-2 text-muted" href="#">호텔 소개</a>
          <a class="p-2 text-muted" href="#">요청 및 문의</a>
        </nav>
      </div>
      
      {% block content %}
      {% endblock %}



    <footer class="blog-footer">
      <p>Team.Normal 1 (A1)</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'holder.min.js' %}"></script>

    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

hotelsite/guest/templates/guest/guest_home.html
{% extends 'guest/guest_base.html' %}
{% load staticfiles %}

{% block content %}
      <div class="row mb-5">
          <div class="col-md-12">
  
            <div class="block-32">
              <form action="#">
                <div class="row">
                  <div class="col-md-6 mb-3 mb-lg-0 col-lg-3">
                    <label for="checkin">Check In</label>
                    <div class="field-icon-wrap">
                      
                      <input type="date" id="checkin_date" class="form-control">
                    </div>
                    <!--하..나도 달력 뜨게 하고싶어....-->
                  </div>
                  <div class="col-md-6 mb-3 mb-lg-0 col-lg-3">
                    <label for="checkin">Check Out</label>
                    <div class="field-icon-wrap">
                      
                      <input type="date" id="checkout_date" class="form-control">
                    </div>
                  </div>
                  <div class="col-md-6 mb-3 mb-md-0 col-lg-3">
                    <div class="row">
                      <div class="col-md-6 mb-3 mb-md-0">
                        <label for="checkin">Adults</label>
                        <div class="field-icon-wrap">
                          <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                          <select name="" id="" class="form-control">
                            <option value="">1</option>
                            <option value="">2</option>
                            <option value="">3</option>
                            <option value="">4+</option>
                          </select>
                        </div>
                      </div>
                      <div class="col-md-6 mb-3 mb-md-0">
                        <label for="checkin">Children</label>
                        <div class="field-icon-wrap">
                          <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                          <select name="" id="" class="form-control">
                            <option value="">1</option>
                            <option value="">2</option>
                            <option value="">3</option>
                            <option value="">4+</option>
                          </select>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 col-lg-3 align-self-end">
                    <button class="btn btn-primary btn-block">Check Availabilty</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark" style = "background-image: url('{% static 'hotel.png' %}');">
        
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">Whelcome to our hotel.</h1>
          <p class="lead my-3">고객님들께 최상의 품질의 서비스와 환경을 제공하기 위해 항상 노력하고 있습니다.</p>
          <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">방 둘러보기</a></p>
        </div>
      </div>

    
    {% endblock %}

hotelsite/guest/templates/guest/guest_myinfo.html
{% extends 'guest/guest_base.html' %}
{% load staticfiles %}

{% block content %}
{% endblock %}

hotelsite/guest/templates/guest/guest_room.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'Wallpaper_2560x1440.jpg' %}">

    <title>Hotel Guest</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'blog.css' %}" rel="stylesheet">
    <style>
      .blog-footer{text-align: center; width:1280px; margin: auto;}
    </style>

  </head>

  <body>

    <div class="container">


      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#"></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="#">Hotel</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">

            <a class="btn btn-sm btn-outline-secondary" href="#">logout</a>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="#">내 정보</a>
          <a class="p-2 text-muted" href="#">예약 확인</a>
          <a class="p-2 text-muted" href="#">직원 검색</a>
          <a class="p-2 text-muted" href="#">방 정보</a>
          <a class="p-2 text-muted" href="#">호텔 소개</a>
          <a class="p-2 text-muted" href="#">요청 및 문의</a>
        </nav>
      </div>

      {% block content %}
      </p>
      <link rel="icon" src="{% static 'Wallpaper_2560x1440.ico' %}">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{% static 'Standard Single Room.jpg' %}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">Standard Single Room</p>

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <small class="text-muted">1박 당 ₩ 101,162 </small>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary">예약하기</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{% static 'Standard Twin Room.jpg' %}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">Standard Twin Room</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <small class="text-muted">1박 당 ₩ 115,856 </small>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary">예약하기</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{% static 'Superior Double Room.jpg' %}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">Superior Double Room</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <small class="text-muted">1박 당 ₩ 125,725</small>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary">예약하기</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{% static 'Standard Triple Room.jpg' %}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">Standard Triple Room</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <small class="text-muted">1박 당 ₩ 149,416</small>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary">예약하기</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{% static 'Superior Triple Room.jpg' %}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">Superior Triple Room</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <small class="text-muted">1박 당 ₩ 160,998</small>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary">예약하기</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{% static 'Standard Quadruple Room.jpg' %}" alt="Card image cap">
            <div class="card-body">
              <p class="card-text">Standard Quadruple Room</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <small class="text-muted">1박 당 ₩ 207,338</small>
                </div>
                <button type="button" class="btn btn-sm btn-outline-secondary">예약하기</button>
              </div>
            </div>
          </div>
        </div>

      <img class="card-img-top" src="{% static 'hotelview.png' %}" alt="Card image cap">
      {% endblock %}


    <footer class="blog-footer">
      <p>Team.Normal 1 (A1)</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'jquery.slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'holder.min.js' %}"></script>

    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

hotelsite/login/templates/sign_in/index.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{% static 'Wallpaper_2560x1440.ico' %}">
        <title>호텔 로그인</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'signin.css' %}" rel="stylesheet">
    </head>

    <body class="text-center">
        <form class="form-signin" action="{% url 'login:sign_in' %}" method="POST"> {% csrf_token %}
        <img class="mb-4" src="{% static 'Wallpaper_2560x1440.jpg' %}" alt="" width="100" height="100">
        <h1 class="h3 mb-3 font-weight-normal">환영합니다!</h1>
        <label for="inputEmail" class="sr-only">아이디</label>
        <input type="id" id="inputEmail" class="form-control" placeholder="아이디" required autofocus name="username">
        <label for="inputPassword" class="sr-only">비밀번호</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="비밀번호" required name="password">
        <div class="checkbox mb-3">
            <label>
            <input type="checkbox" value="remember-me"> 로그인 정보 기억
            </label>
        </div>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="로그인"></input>
        <p class="mt-5 mb-3 text-muted">&copy; 2018</p>
        </form>
    </body>
</html>

hotelsite/login/templates/sign_in/log_in.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{% static 'Wallpaper_2560x1440.ico' %}">
        <title>호텔 로그인</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'signin.css' %}" rel="stylesheet">
    </head>

    <body class="text-center">
        <form class="form-signin" action="{% url 'login:sign_in' %}" method="POST"> {% csrf_token %}
        <img class="mb-4" src="{% static 'Wallpaper_2560x1440.jpg' %}" alt="" width="100" height="100">
        <h1 class="h3 mb-3 font-weight-normal">환영합니다!</h1>
        <label for="inputEmail" class="sr-only">아이디</label>
        <input type="id" id="inputEmail" class="form-control" placeholder="아이디" required autofocus name="username">
        <label for="inputPassword" class="sr-only">비밀번호</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="비밀번호" required name="password">
        <div class="checkbox mb-3">
            <label>
            <input type="checkbox" value="remember-me"> 로그인 정보 기억
            </label>
        </div>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="로그인"></input>
        <p class="mt-5 mb-3 text-muted">&copy; 2018</p>
        </form>
    </body>
</html>

hotelsite/login/templates/sign_in/sign_up.html
<html>
    <h2>회원가입</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="회원가입" />
    </form>
        
</html>

hotelsite/login/templates/sign_in/test.html
<html>
    <p>this is test page</p>
</html>

hotelsite/staff/templates/staff/guest_req.html
{% extends 'staff/staff_base.html' %} 
{% load staticfiles %} 

{% block content %} 
<a href = "{% url 'staff:post_new' %}" class="btn btn-secondary">요청접수</a>
<div class="row">
    <div class="col-3">고객</div>
    <div class="col-6">요청사항</div>
    <div class="col-3">처리 여부</div>
</div>
{% for post in posts %} 
<div class="row"> 
    <div class="col-3">{{post.author}}</div>
    <a href = "{% url 'staff:post_detail' pk=post.pk %}" class="col-6">{{post.title}}</a>
    <div class="col-3">{{post.get_handle_or_not_display}}</div>
</div>
{% endfor %} 
{% endblock %}  

hotelsite/staff/templates/staff/req_edit.html
{% extends 'staff/staff_base.html' %}
{% load staticfiles %}

{% block content %}
<form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
<button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

hotelsite/staff/templates/staff/reservation_status.html
<html>
    <h1>reservation_status</h1>
</html>

hotelsite/staff/templates/staff/staff_base.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'Wallpaper_2560x1440.ico' %}">

    <title>Hotel Staff</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{% static 'blog.css' %}" rel="stylesheet">
</head>
<body>
        <div class="container">

            <header class="blog-header py-3">
                <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 pt-1">
                    <a class="text-muted" href="#"></a>
                </div>
                <div class="col-4 text-center">
                    <a class="blog-header-logo text-dark" href="{% url 'staff:staff_home' %}">Hotel</a>
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'staff:logout' %}">logout</a>
                </div>
                </div>
            </header>

            <div class="nav-scroller py-1 mb-2">
                <nav class="nav d-flex justify-content-between">
                <a class="p-2 text-muted" href="#">내 정보</a>
                <a class="p-2 text-muted" href="#">객실</a>
                <a class="p-2 text-muted" href="#">직원</a>
                <a class="p-2 text-muted" href="#">예약현황</a>
                <a class="p-2 text-muted" href="{% url 'staff:guest_req' %}">고객 요청</a> 
                <a class="p-2 text-muted" href="#">직원 게시판</a>
                </nav>
            </div>
            
            {% block content %}
            {% endblock %}


<!--
            <footer class="blog-footer">
            <p>Team.Normal 1 (A1)</p>
            <p>
                <a href="#">Back to top</a>
            </p>
            </footer>
-->
            <!-- Bootstrap core JavaScript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="http://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script>window.jQuery || document.write('<script src="{% static 'jquery.slim.min.js' %}"><\/script>')</script>
            <script src="{% static 'popper.min.js' %}"></script>
            <script src="{% static 'bootstrap.min.js' %}"></script>
            <script src="{% static 'holder.min.js' %}"></script>

            <script>
            Holder.addTheme('thumb', {
                bg: '#55595c',
                fg: '#eceeef',
                text: 'Thumbnail'
            });
            </script>
        </div>
</body>
</html>